version: '3.8'

services:
  app:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - mosquitto
    networks:
      - mqtt-net

  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - mqtt-net

networks:
  mqtt-net:

volumes:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:
